#!/usr/bin/env bash
#SSH Client Configuration

Host *
   PasswordAuthentication no
   IdentityFile ~/ssh/school
   SenEnv LANG LC_*
   HashKnownHosts yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
